services:
  pgvector_db:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    environment:
      POSTGRES_DB: pgvector_db
      POSTGRES_USER: pgvector_db
      POSTGRES_PASSWORD: pgvector_db
    # DATABASE_URL === postgres://pgvector_db:pgvector_db@db:5432/pgvector_db
    ports:
      - "5432:5432"
    volumes:
      - pgvector_db_data:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always

  redis_cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_cache_data:/data
    restart: unless-stopped

  otel_lgtm:
    image: docker.io/grafana/otel-lgtm:latest
    ports:
      - "3111:3000" # Grafana UI
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    volumes:
      - ./docker/container/grafana:/data/grafana
      - ./docker/container/prometheus:/data/prometheus
      - ./docker/container/loki:/data/loki
    environment:
      - GF_PATHS_DATA=/data/grafana
    env_file:
      - ./docker/.env
    # stdin_open: true
    # tty: true

# Stores data outside the container to ensure persistence
volumes:
  pgvector_db_data:
  redis_cache_data: 