receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        
processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  # Data sources: traces, metrics, logs
  # file:
  #   path: ./otel-collector-data.json
  # otlp:
  #   endpoint: otel_collector:4317 # this will self-referencing
  #   tls:
  #     insecure: true  # for local development
  # prometheus:
  #   endpoint: "0.0.0.0:8889"

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # otlp
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # otlp, prometheus
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # otlp
