# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

description: "Hono AI"
outputPath: "evals/.results/hono.json"

providers:
  - id: file://../custom-provider.ts
    label: gemini-2.5-flash-preview-05-20
    prompts: ["translator"]
    config:
      model: gemini-2.5-flash-preview-05-20

prompts:
  - id: file://../prompts/translator.json
    label: translator

tests:
  - vars:
      targetLanguage: Indonesian
      text: Hello World
    assert:
      - type: contains
        value: "Halo"
      - type: contains
        value: "Hai"
      - type: contains
        value: "Dunia"
